export const ACCESS_LOG_ACTION = {
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  CHILD_CREATED: 'CHILD_CREATED',
  APPLICATION_VIEWED: 'APPLICATION_VIEWED',
  ENROLLMENT_CREATED: 'ENROLLMENT_CREATED',
  ENROLLMENT_FEE_UPDATED: 'ENROLLMENT_FEE_UPDATED',
  LESSON_CREATED: 'LESSON_CREATED',
  LESSON_UPDATED: 'LESSON_UPDATED',
  LESSON_DELETED: 'LESSON_DELETED',
  LESSON_CLONED: 'LESSON_CLONED',
  LESSON_VIEWED: 'LESSON_VIEWED',
} as const;

export type AccessLogAction = typeof ACCESS_LOG_ACTION[keyof typeof ACCESS_LOG_ACTION];

export const ACCESS_LOG_TARGET_TYPE = {
  APPLICATION: 'APPLICATION',
  CHILD: 'CHILD',
  PARENT: 'PARENT',
  ENROLLMENT: 'ENROLLMENT',
  LESSON: 'LESSON',
} as const;

export type AccessLogTargetType = typeof ACCESS_LOG_TARGET_TYPE[keyof typeof ACCESS_LOG_TARGET_TYPE];

export const ACCESS_LOG_ACTION_LABELS = {
  [ACCESS_LOG_ACTION.APPLICATION_APPROVED]: 'Application Approved',
  [ACCESS_LOG_ACTION.APPLICATION_REJECTED]: 'Application Rejected',
  [ACCESS_LOG_ACTION.CHILD_CREATED]: 'Child Profile Created',
  [ACCESS_LOG_ACTION.APPLICATION_VIEWED]: 'Application Viewed',
  [ACCESS_LOG_ACTION.ENROLLMENT_CREATED]: 'Enrollment Created',
  [ACCESS_LOG_ACTION.ENROLLMENT_FEE_UPDATED]: 'Enrollment Fee Updated',
  [ACCESS_LOG_ACTION.LESSON_CREATED]: 'Lesson Created',
  [ACCESS_LOG_ACTION.LESSON_UPDATED]: 'Lesson Updated',
  [ACCESS_LOG_ACTION.LESSON_DELETED]: 'Lesson Deleted',
  [ACCESS_LOG_ACTION.LESSON_CLONED]: 'Lesson Cloned',
  [ACCESS_LOG_ACTION.LESSON_VIEWED]: 'Lesson Viewed',
} as const;