export const ACCESS_LOG_ACTION = {
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  CHILD_CREATED: 'CHILD_CREATED',
  APPLICATION_VIEWED: 'APPLICATION_VIEWED',
} as const;

export type AccessLogAction = typeof ACCESS_LOG_ACTION[keyof typeof ACCESS_LOG_ACTION];

export const ACCESS_LOG_TARGET_TYPE = {
  APPLICATION: 'APPLICATION',
  CHILD: 'CHILD',
  PARENT: 'PARENT',
} as const;

export type AccessLogTargetType = typeof ACCESS_LOG_TARGET_TYPE[keyof typeof ACCESS_LOG_TARGET_TYPE];

export const ACCESS_LOG_ACTION_LABELS = {
  [ACCESS_LOG_ACTION.APPLICATION_APPROVED]: 'Application Approved',
  [ACCESS_LOG_ACTION.APPLICATION_REJECTED]: 'Application Rejected',
  [ACCESS_LOG_ACTION.CHILD_CREATED]: 'Child Profile Created',
  [ACCESS_LOG_ACTION.APPLICATION_VIEWED]: 'Application Viewed',
} as const;