export const RELATIONSHIP_TYPE = {
  MOTHER: 'MOTHER',
  FATHER: 'FATHER',
  GUARDIAN: 'GUARDIAN',
  OTHER: 'OTHER',
} as const;

export type RelationshipType = typeof RELATIONSHIP_TYPE[keyof typeof RELATIONSHIP_TYPE];

export const RELATIONSHIP_TYPE_LABELS = {
  [RELATIONSHIP_TYPE.MOTHER]: 'Mother',
  [RELATIONSHIP_TYPE.FATHER]: 'Father',
  [RELATIONSHIP_TYPE.GUARDIAN]: 'Guardian',
  [RELATIONSHIP_TYPE.OTHER]: 'Other',
} as const;

export const RELATIONSHIP_TYPE_OPTIONS = [
  { value: RELATIONSHIP_TYPE.MOTHER, label: RELATIONSHIP_TYPE_LABELS[RELATIONSHIP_TYPE.MOTHER] },
  { value: RELATIONSHIP_TYPE.FATHER, label: RELATIONSHIP_TYPE_LABELS[RELATIONSHIP_TYPE.FATHER] },
  { value: RELATIONSHIP_TYPE.GUARDIAN, label: RELATIONSHIP_TYPE_LABELS[RELATIONSHIP_TYPE.GUARDIAN] },
  { value: RELATIONSHIP_TYPE.OTHER, label: RELATIONSHIP_TYPE_LABELS[RELATIONSHIP_TYPE.OTHER] },
] as const;