openapi: 3.0.3
info:
  title: Teacher Module API
  description: API endpoints for Teacher dashboard and student roster functionality
  version: 1.0.0

paths:
  /api/teacher/dashboard:
    get:
      summary: Get Teacher dashboard data
      description: Retrieve dashboard metrics and overview data for authenticated Teacher
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  teacherId:
                    type: string
                    format: uuid
                  teacherName:
                    type: string
                  metrics:
                    type: object
                    properties:
                      totalStudents:
                        type: integer
                      activeStudents:
                        type: integer
                      inactiveStudents:
                        type: integer
                  lastUpdated:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized - not authenticated
        '403':
          description: Forbidden - not a Teacher role
        '500':
          description: Internal server error

  /api/teacher/students:
    get:
      summary: Get Teacher's student roster
      description: Retrieve all students assigned to the authenticated Teacher
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          description: Filter by student enrollment status
          required: false
          schema:
            type: string
            enum: [ACTIVE, INACTIVE, ALL]
            default: ALL
        - name: classGroup
          in: query
          description: Filter by class/group identifier
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Student roster retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  students:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        firstName:
                          type: string
                        lastName:
                          type: string
                        enrollmentStatus:
                          type: string
                          enum: [ACTIVE, INACTIVE, GRADUATED, WITHDRAWN]
                        classGroup:
                          type: string
                          nullable: true
                        assignedAt:
                          type: string
                          format: date-time
                        statusUpdatedAt:
                          type: string
                          format: date-time
                  totalCount:
                    type: integer
                  classGroups:
                    type: array
                    items:
                      type: string
        '401':
          description: Unauthorized - not authenticated
        '403':
          description: Forbidden - not a Teacher role
        '500':
          description: Internal server error

  /api/teacher/profile:
    get:
      summary: Get Teacher profile information
      description: Retrieve profile data for authenticated Teacher
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Teacher profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  userId:
                    type: string
                    format: uuid
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                    format: email
                  schoolId:
                    type: string
                    format: uuid
                  schoolName:
                    type: string
                  assignmentCount:
                    type: integer
                  createdAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized - not authenticated
        '403':
          description: Forbidden - not a Teacher role
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time